include(CPM)

# Release tarballs, not git clones, and it is worth saying why once rather than
# three times: this was 98 of the 105 seconds a cold configure used to take.
#
# A grammar's `src/parser.c` is *generated*, and it is 16 MB. Every release
# rewrites the whole file, so git stores a fresh 16 MB blob per tag —
# tree-sitter-cpp carries 96 MB of history behind a 17 MB working tree, and
# cloning it alone took 79 s to reach three files.
#
# GIT_SHALLOW does not fix it. CMake's ExternalProject clones with
# `--depth 1 --no-single-branch`, so that a GIT_TAG naming any ref can still be
# checked out afterwards — which fetches the depth-1 tip of *every* branch and
# tag, and every one of those tips has its own 16 MB parser.c. Measured: 88 MB
# and 85 s full, 28 MB and 79 s shallow. Barely moved. (CPM would have set
# GIT_SHALLOW on its own here, since these tags are not commit hashes, but only
# inside its CPM_SOURCE_CACHE branch — so with no cache configured you get full
# clones and no warning either way.)
#
# A tarball has no history at all: 2.4 MB and about 2 s for all three.
#
# URL_HASH is the tradeoff to know about. It buys integrity, and it costs a
# build that fails loudly if GitHub ever regenerates an archive — which it has
# done once, in 2023, when it changed compression and broke pinned hashes across
# the ecosystem. A loud failure fixed by one line is the better end of that
# trade for a dependency carrying a parser we execute.

# tree-sitter's own CMakeLists declares BUILD_SHARED_LIBS as a *cache* option
# defaulting to ON, so leaving it alone both makes tree-sitter shared and leaks
# the setting to every CPM package configured after it. A plain normal variable
# wins (its cmake_minimum_required puts CMP0077 in NEW mode) and keeps the cache
# clean. ECode links static libraries into a GUI executable, like eacp does.
set(BUILD_SHARED_LIBS OFF)

CPMAddPackage(
        NAME tree-sitter
        VERSION 0.26.11
        URL https://github.com/tree-sitter/tree-sitter/archive/refs/tags/v0.26.11.tar.gz
        URL_HASH SHA256=1bab01ed21464f3272665b9c60e39ee79f68da1333e80b23f2c9356569d06971)

# The grammars are DOWNLOAD_ONLY on purpose.
#
# tree-sitter-cpp ships a CMakeLists, but it runs find_program(tree-sitter) and
# registers a rule regenerating src/parser.c from src/grammar.json. A git
# checkout gives both files the same mtime, so the rule always fires and the
# build dies on the Rust CLI we deliberately do not depend on. The checked-in
# parser.c is complete; compiling it directly avoids the whole problem.
CPMAddPackage(
        NAME tree-sitter-cpp
        VERSION 0.23.4
        URL https://github.com/tree-sitter/tree-sitter-cpp/archive/refs/tags/v0.23.4.tar.gz
        URL_HASH SHA256=7a2c55afe3028f4105f25762ea58cc16537d1f5a1dcd9cca90410b3cd5d46051
        DOWNLOAD_ONLY YES)

# Fetched only for queries/highlights.scm. C++ highlighting is officially C's
# query file followed by C++'s — tree-sitter.json lists them in that order — and
# the C++ file alone is 12 patterns with no comments, numbers or operators.
CPMAddPackage(
        NAME tree-sitter-c
        VERSION 0.24.2
        URL https://github.com/tree-sitter/tree-sitter-c/archive/refs/tags/v0.24.2.tar.gz
        URL_HASH SHA256=2eeb4db31f8fa0865e45488503d13403923bcb485a1bdb637abff8c42dd97364
        DOWNLOAD_ONLY YES)

if (NOT TARGET ts-grammar-cpp)
    # scanner.c as well as parser.c: this grammar has an external scanner. The
    # include dir is src/, not src/tree_sitter/ — parser.c includes
    # "tree_sitter/parser.h" and those headers are vendored one level down.
    add_library(ts-grammar-cpp STATIC
            "${tree-sitter-cpp_SOURCE_DIR}/src/parser.c"
            "${tree-sitter-cpp_SOURCE_DIR}/src/scanner.c")

    target_include_directories(ts-grammar-cpp
            PRIVATE "${tree-sitter-cpp_SOURCE_DIR}/src")

    set_target_properties(ts-grammar-cpp PROPERTIES
            C_STANDARD 11
            POSITION_INDEPENDENT_CODE ON)

    # Generated parsers are not written to anyone's warning standards.
    if (NOT MSVC)
        target_compile_options(ts-grammar-cpp PRIVATE -w)
    endif ()
endif ()

# The two query files, baked into a translation unit so the app carries its own
# highlighting rules rather than reading them from a CPM checkout at runtime.
set(ECODE_HIGHLIGHT_QUERY_CPP "${CMAKE_BINARY_DIR}/generated/CppHighlightQuery.cpp")

if (NOT EXISTS "${ECODE_HIGHLIGHT_QUERY_CPP}")
    file(READ "${tree-sitter-c_SOURCE_DIR}/queries/highlights.scm" ECODE_C_QUERY)
    file(READ "${tree-sitter-cpp_SOURCE_DIR}/queries/highlights.scm" ECODE_CPP_QUERY)

    file(WRITE "${ECODE_HIGHLIGHT_QUERY_CPP}"
            "// Generated by CMake from tree-sitter-c and tree-sitter-cpp.\n"
            "// Edit FindTreeSitter.cmake, not this file.\n\n"
            "namespace ecode\n{\n"
            "extern const char* const cppHighlightQuery;\n\n"
            "const char* const cppHighlightQuery = R\"ECODEQUERY(\n"
            "${ECODE_C_QUERY}\n${ECODE_CPP_QUERY}\n"
            ")ECODEQUERY\";\n"
            "} // namespace ecode\n")
endif ()
