include(CPM)

# tree-sitter's own CMakeLists declares BUILD_SHARED_LIBS as a *cache* option
# defaulting to ON, so leaving it alone both makes tree-sitter shared and leaks
# the setting to every CPM package configured after it. A plain normal variable
# wins (its cmake_minimum_required puts CMP0077 in NEW mode) and keeps the cache
# clean. ECode links static libraries into a GUI executable, like eacp does.
set(BUILD_SHARED_LIBS OFF)

CPMAddPackage(
        NAME tree-sitter
        GITHUB_REPOSITORY tree-sitter/tree-sitter
        GIT_TAG v0.26.11)

# The grammars are DOWNLOAD_ONLY on purpose.
#
# tree-sitter-cpp ships a CMakeLists, but it runs find_program(tree-sitter) and
# registers a rule regenerating src/parser.c from src/grammar.json. A git
# checkout gives both files the same mtime, so the rule always fires and the
# build dies on the Rust CLI we deliberately do not depend on. The checked-in
# parser.c is complete; compiling it directly avoids the whole problem.
CPMAddPackage(
        NAME tree-sitter-cpp
        GITHUB_REPOSITORY tree-sitter/tree-sitter-cpp
        GIT_TAG v0.23.4
        DOWNLOAD_ONLY YES)

# Fetched only for queries/highlights.scm. C++ highlighting is officially C's
# query file followed by C++'s — tree-sitter.json lists them in that order — and
# the C++ file alone is 12 patterns with no comments, numbers or operators.
CPMAddPackage(
        NAME tree-sitter-c
        GITHUB_REPOSITORY tree-sitter/tree-sitter-c
        GIT_TAG v0.24.2
        DOWNLOAD_ONLY YES)

if (NOT TARGET ts-grammar-cpp)
    # scanner.c as well as parser.c: this grammar has an external scanner. The
    # include dir is src/, not src/tree_sitter/ — parser.c includes
    # "tree_sitter/parser.h" and those headers are vendored one level down.
    add_library(ts-grammar-cpp STATIC
            "${tree-sitter-cpp_SOURCE_DIR}/src/parser.c"
            "${tree-sitter-cpp_SOURCE_DIR}/src/scanner.c")

    target_include_directories(ts-grammar-cpp
            PRIVATE "${tree-sitter-cpp_SOURCE_DIR}/src")

    set_target_properties(ts-grammar-cpp PROPERTIES
            C_STANDARD 11
            POSITION_INDEPENDENT_CODE ON)

    # Generated parsers are not written to anyone's warning standards.
    if (NOT MSVC)
        target_compile_options(ts-grammar-cpp PRIVATE -w)
    endif ()
endif ()

# The two query files, baked into a translation unit so the app carries its own
# highlighting rules rather than reading them from a CPM checkout at runtime.
set(ECODE_HIGHLIGHT_QUERY_CPP "${CMAKE_BINARY_DIR}/generated/CppHighlightQuery.cpp")

if (NOT EXISTS "${ECODE_HIGHLIGHT_QUERY_CPP}")
    file(READ "${tree-sitter-c_SOURCE_DIR}/queries/highlights.scm" ECODE_C_QUERY)
    file(READ "${tree-sitter-cpp_SOURCE_DIR}/queries/highlights.scm" ECODE_CPP_QUERY)

    file(WRITE "${ECODE_HIGHLIGHT_QUERY_CPP}"
            "// Generated by CMake from tree-sitter-c and tree-sitter-cpp.\n"
            "// Edit FindTreeSitter.cmake, not this file.\n\n"
            "namespace ecode\n{\n"
            "extern const char* const cppHighlightQuery;\n\n"
            "const char* const cppHighlightQuery = R\"ECODEQUERY(\n"
            "${ECODE_C_QUERY}\n${ECODE_CPP_QUERY}\n"
            ")ECODEQUERY\";\n"
            "} // namespace ecode\n")
endif ()
